services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:16                    # Usa a imagem oficial do PostgreSQL na versão 16
    container_name: postgres-pix-db           # Nome do container do banco de dados
    environment:
      POSTGRES_DB: pix_db                 # Nome do banco de dados a ser criado
      POSTGRES_USER: postgres             # Usuário padrão do banco de dados
      POSTGRES_PASSWORD: qwe123           # Senha do banco de dados (definida como variável de ambiente)
    ports:
      - "5433:5432"                       # Mapeia a porta 5432 do container para a porta 5433 do host
    volumes:
      - db-data:/var/lib/postgresql/data  # Armazena os dados do banco de forma persistente em um volume
    networks:
      - pix-network                       # Adicionado à rede personalizada

  # Serviço da API SysAgua
  pix-api:
    build:
      context: ./backend                 # Define o diretório do código-fonte da API para o build do Docker
    container_name: pix-api               # Nome do container da API
    environment:
      SPRING_PROFILES_ACTIVE: prod      # Perfil ativo do Spring
      DB_URL: jdbc:postgresql://postgres-pix-db:5432/pix_db  # URL de conexão com o banco de dados
      DB_USERNAME: postgres               # Nome de usuário do banco de dados
      DB_PASSWORD: qwe123                 # Senha padrão para autenticação
      JWT_SECRET: ${JWT_SECRET}   # Chave secreta para geração de tokens JWT
    depends_on:
      - db                                # Garante que o serviço do banco de dados esteja disponível antes da API iniciar
    ports:
      - "8080:8080"                       # Mapeia a porta 8080 do container para a porta 8080 do host
    networks:
      - pix-network                       # Adicionado à rede personalizada


networks:
  pix-network:                            # Definição da rede personalizada
    driver: bridge

# Volumes persistentes
volumes:
  db-data:                                # Volume para armazenamento persistente dos dados do banco de dados
