name: Continuous Integration

on:
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: qwe123

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Build application with Gradle
        run: ./gradlew clean build -x test
        working-directory: backend

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Wait for application to be ready
        run: |
          for i in {1..60}; do
            if docker exec pix-api curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "Application is ready!"
              exit 0
            fi
            echo "Waiting for application to be ready..."
            sleep 2
          done
          echo "Application failed to start in time"
          exit 1
        

      - name: Check Docker logs
        run: docker-compose logs
        
      - name: Run tests
        run: ./gradlew test
        working-directory: backend


      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
