name: Continuous Integration

on:
  push:
    branches:
      - staging
      - develop
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run services with Docker Compose
        run: |
          docker-compose up -d --build
          docker-compose ps

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5433 -U postgres; then
              echo "PostgreSQL is ready!";
              exit 0;
            fi;
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done;
          exit 1;

      - name: Run tests with Gradle
        run: |
          docker exec pix-api ./gradlew clean build

      - name: Stop Docker Compose
        run: docker-compose down
