name: Continuous Integration

on:
  push:
    branches:
      - staging         # Executa o workflow quando houver um push para a branch 'staging'
      - develop
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: pix_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwe123
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Versão do Java
          distribution: 'temurin'

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!";
              exit 0;
            fi;
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done;
          exit 1;

      - name: Run tests with Gradle
        run: |
          ./gradlew clean build
